import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { ApiError, apiRequest, resolveApiUrl } from '../../api/client';
import type { PdfIssuance, PdfIssuanceDetail, PdfTemplate, PdfTemplateDetail } from './types';
function auth(token: string | null): string { if (!token?.trim()) throw new ApiError('로그인이 필요합니다.', 401); return token.trim(); }
export async function listPdfTemplates(token: string | null) { return apiRequest<{ templates: PdfTemplate[] }>('/api/pdf-templates', { token: auth(token) }); }
export async function getPdfTemplate(token: string | null, id: number) { return apiRequest<PdfTemplateDetail>(`/api/pdf-templates/${id}`, { token: auth(token) }); }
export async function listPdfIssuances(token: string | null) { return apiRequest<{ issuances: PdfIssuance[] }>('/api/pdf-issuances', { token: auth(token) }); }
export async function getPdfIssuance(token: string | null, id: number) { return apiRequest<{ issuance: PdfIssuanceDetail }>(`/api/pdf-issuances/${id}`, { token: auth(token) }); }
async function fetchPdf(token: string | null, path: string, init?: RequestInit): Promise<Uint8Array> { const response = await fetch(resolveApiUrl(path), { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${auth(token)}`, ...(init?.headers ?? {}) } }); if (!response.ok) { const data = await response.json().catch(() => ({})) as { message?: string }; throw new ApiError(data.message || 'PDF를 처리하지 못했습니다.', response.status); } return new Uint8Array(await response.arrayBuffer()); }
export async function renderAndSharePdf(token: string | null, template: PdfTemplate, values: Record<string, string>, customerId: number | null) { const bytes = await fetchPdf(token, `/api/pdf-templates/${template.id}/render`, { method: 'POST', body: JSON.stringify({ values, ...(customerId ? { customerId, issuanceCustomerId: customerId } : {}) }) }); const file = new File(Paths.cache, `${template.code || 'onefc'}-${Date.now()}.pdf`); file.create({ overwrite: true }); file.write(bytes); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: 'application/pdf', dialogTitle: `${template.title} PDF` }); return file.uri; }
export async function shareIssuedPdf(token: string | null, row: PdfIssuance, fileName: string) { const bytes = await fetchPdf(token, `/api/pdf-issuances/${row.id}/file`); const file = new File(Paths.cache, fileName); file.create({ overwrite: true }); file.write(bytes); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: 'application/pdf', dialogTitle: row.templateTitle }); return file.uri; }
