import { useMemo, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useMutation, useQuery } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthProvider';
import { AppHeader } from '../../components/AppHeader';
import { ErrorState } from '../../components/ErrorState';
import { AppText, Badge, Button, Card, Inline, Screen, Stack, TextField, useAppTheme, type AppTheme } from '../../design-system';
import { formatPdfBytes, safePdfFileName } from './applicationDocumentsModel';
import { listPdfIssuances, shareIssuedPdf } from './applicationDocumentsApi';
import type { PdfIssuance } from './types';

export function ApplicationHistoryScreen() { const { token } = useAuth(); const router = useRouter(); const theme = useAppTheme(); const styles = useMemo(() => makeStyles(theme), [theme]); const [search, setSearch] = useState(''); const query = useQuery({ queryKey: ['pdf-issuances'], queryFn: () => listPdfIssuances(token), enabled: Boolean(token) }); const rows = (query.data?.issuances ?? []).filter((row) => !search.trim() || `${row.templateTitle} ${row.customerLabel ?? ''}`.toLowerCase().includes(search.trim().toLowerCase())); const share = useMutation({ mutationFn: (row: PdfIssuance) => shareIssuedPdf(token, row, safePdfFileName(row.templateCode, row.id)) }); return <View style={styles.root}><AppHeader title="신청서 작성내역" /><Screen padded={false}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} colors={[theme.colors.primary]} tintColor={theme.colors.primary} />}><Card><Stack gap="md"><AppText variant="heading">과거 발급 신청서</AppText><AppText variant="caption">보관된 원본 PDF를 다시 받거나 과거 입력값으로 새 문서를 작성합니다.</AppText><TextField placeholder="문서 · 고객 검색" value={search} onChangeText={setSearch} /><Button label="새 신청서 작성" variant="secondary" onPress={() => router.push('/application/documents')} /></Stack></Card>{query.isError ? <ErrorState title="발급 이력을 불러오지 못했습니다" message={query.error instanceof Error ? query.error.message : '잠시 후 다시 시도해 주세요.'} onRetry={() => void query.refetch()} /> : null}{!query.isLoading && !rows.length ? <Card variant="outlined"><AppText color="textSecondary" align="center">아직 발급한 문서가 없습니다.</AppText></Card> : null}{rows.map((row) => <Card key={row.id} variant="outlined"><Stack gap="sm"><Inline justify="space-between" align="flex-start"><View style={styles.grow}><AppText variant="bodyStrong">{row.templateTitle}</AppText><AppText variant="caption">#{row.id} · {row.customerLabel || '고객 미지정'} · {new Date(row.createdAt).toLocaleString('ko-KR')}</AppText></View><Badge label={formatPdfBytes(row.byteLength)} tone="info" /></Inline><Inline><Button label="PDF 받기" size="sm" loading={share.isPending && share.variables?.id === row.id} onPress={() => share.mutate(row)} /><Button label="내용 불러오기" size="sm" variant="secondary" disabled={!row.templateId} onPress={() => router.push({ pathname: '/application/documents', params: { sourceIssuanceId: String(row.id) } })} /></Inline></Stack></Card>)}</ScrollView></Screen></View>; }
function makeStyles(theme: AppTheme) { return StyleSheet.create({ root: { flex: 1, backgroundColor: theme.colors.background }, grow: { flex: 1 }, content: { padding: theme.spacing.lg, paddingBottom: theme.spacing.huge, gap: theme.spacing.md } }); }
