import { ApiError, apiRequest, resolveApiUrl } from '../../api/client';
import type { CustomerFile, Consultation } from './types';
function auth(token: string | null): string { if (!token?.trim()) throw new ApiError('로그인이 필요합니다.', 401); return token.trim(); }
export async function listConsultations(token: string | null, customerId: number) { return apiRequest<Consultation[]>(`/api/customers/${customerId}/consultations?limit=200`, { token: auth(token) }); }
export async function createConsultation(token: string | null, customerId: number, payload: Omit<Consultation, 'id' | 'customerId' | 'createdAt' | 'updatedAt'>) { return apiRequest<Consultation>(`/api/customers/${customerId}/consultations`, { method: 'POST', token: auth(token), body: JSON.stringify(payload) }); }
export async function updateConsultation(token: string | null, customerId: number, id: number, payload: Partial<Consultation>) { return apiRequest<Consultation>(`/api/customers/${customerId}/consultations/${id}`, { method: 'PATCH', token: auth(token), body: JSON.stringify(payload) }); }
export async function deleteConsultation(token: string | null, customerId: number, id: number) { await apiRequest(`/api/customers/${customerId}/consultations/${id}`, { method: 'DELETE', token: auth(token) }); }
export async function listCustomerFiles(token: string | null, customerId: number) { return apiRequest<CustomerFile[]>(`/api/storage/files?customerId=${customerId}`, { token: auth(token) }); }
export async function openCustomerFile(token: string | null, id: number) { const result = await apiRequest<{ openUrl: string }>(`/api/storage/files/${id}/open-token`, { method: 'POST', token: auth(token), body: JSON.stringify({}) }); return resolveApiUrl(result.openUrl); }
export async function deleteCustomerFile(token: string | null, id: number) { await apiRequest(`/api/storage/files/${id}`, { method: 'DELETE', token: auth(token) }); }
export async function uploadCustomerFile(token: string | null, customerId: number, asset: { uri: string; name: string; mimeType?: string | null; size?: number }) { const bearer = auth(token); const blob = await fetch(asset.uri).then((response) => response.blob()); const contentType = asset.mimeType || blob.type || 'application/octet-stream'; const size = asset.size ?? blob.size; const presign = await apiRequest<{ fileId: number; uploadUrl: string; fileUrl: string; objectKey: string; putHeaders?: Record<string, string> }>('/api/storage/files/presign', { method: 'POST', token: bearer, body: JSON.stringify({ fileName: asset.name, contentType, size, sizeBytes: size, customerId }) }); const put = await fetch(presign.uploadUrl, { method: 'PUT', headers: { 'Content-Type': contentType, ...(presign.putHeaders ?? {}) }, body: blob }); if (!put.ok) { await apiRequest('/api/storage/files/upload-fail', { method: 'POST', token: bearer, body: JSON.stringify({ fileId: presign.fileId }) }).catch(() => undefined); throw new ApiError('파일 업로드에 실패했습니다.', put.status); } await apiRequest('/api/storage/files', { method: 'POST', token: bearer, body: JSON.stringify({ fileId: presign.fileId, fileName: asset.name, displayName: asset.name, objectKey: presign.objectKey, fileUrl: presign.fileUrl, size, mimeType: contentType, content: '', folderId: null, customerId }) }); }
