import { ApiError, apiRequest } from '../../api/client';
import { normalizeSmsCampaign, normalizeSmsOptOut, normalizeSmsSender, normalizeSmsSettings, normalizeSmsTemplate } from './smsModel';
import type { SmsCampaign, SmsMessageType, SmsOptOut, SmsSender, SmsSettings, SmsTemplate } from './types';
function tokenOf(token: string | null) { if (!token?.trim()) throw new ApiError('로그인이 필요합니다.', 401); return token; }
async function array<T>(path: string, token: string | null, normalize: (value: unknown) => T | null): Promise<T[]> { const rows = await apiRequest<unknown[]>(path, { token: tokenOf(token) }); return rows.map(normalize).filter((row): row is T => Boolean(row)); }
export const getSmsSettings = async (token: string | null) => normalizeSmsSettings(await apiRequest('/api/sms/settings', { token: tokenOf(token) }));
export async function saveSmsSettings(token: string | null, input: { aligoUserId: string; apiKey?: string; defaultSender: string; adDisplayName?: string }): Promise<SmsSettings> { return normalizeSmsSettings(await apiRequest('/api/sms/settings/aligo', { method: 'POST', token: tokenOf(token), body: JSON.stringify({ aligo_user_id: input.aligoUserId, api_key: input.apiKey, default_sender: input.defaultSender, ad_display_name: input.adDisplayName }) })); }
export async function deleteSmsSettings(token: string | null): Promise<void> { await apiRequest('/api/sms/settings/aligo', { method: 'DELETE', token: tokenOf(token) }); }
export const getSmsSenders = (token: string | null): Promise<SmsSender[]> => array('/api/sms/senders', token, normalizeSmsSender);
export const getSmsTemplates = (token: string | null): Promise<SmsTemplate[]> => array('/api/sms/templates', token, normalizeSmsTemplate);
export const getSmsHistory = (token: string | null): Promise<SmsCampaign[]> => array('/api/sms/history', token, normalizeSmsCampaign);
export const getSmsCampaigns = (token: string | null): Promise<SmsCampaign[]> => array('/api/sms/campaigns', token, normalizeSmsCampaign);
export const getSmsOptOuts = (token: string | null): Promise<SmsOptOut[]> => array('/api/sms/opt-outs', token, normalizeSmsOptOut);
export async function getSmsBalance(token: string | null): Promise<string> { const result = await apiRequest<{ success: boolean; balanceText?: string; errorMessage?: string }>('/api/sms/balance', { token: tokenOf(token) }); if (!result.success) throw new ApiError(result.errorMessage || '잔액 조회에 실패했습니다.', 400); return result.balanceText || '잔액 정보 없음'; }
export async function sendSingleSms(token: string | null, input: { senderNumber: string; receiver: string; message: string; messageType: SmsMessageType }): Promise<void> { const result = await apiRequest<{ success: boolean; errorMessage?: string }>('/api/sms/send', { method: 'POST', token: tokenOf(token), body: JSON.stringify({ sender_number: input.senderNumber, receiver: input.receiver, message: input.message, message_type: input.messageType }) }); if (!result.success) throw new ApiError(result.errorMessage || '문자 발송에 실패했습니다.', 400); }
export async function testSms(token: string | null, input: { senderNumber: string; receiver: string; message: string }): Promise<void> { const result = await apiRequest<{ success: boolean; errorMessage?: string }>('/api/sms/test-send', { method: 'POST', token: tokenOf(token), body: JSON.stringify({ sender_number: input.senderNumber, receiver: input.receiver, message: input.message }) }); if (!result.success) throw new ApiError(result.errorMessage || '테스트 발송에 실패했습니다.', 400); }
export async function createSmsTemplate(token: string | null, input: { title: string; message: string; messageType: SmsMessageType }): Promise<void> { await apiRequest('/api/sms/templates', { method: 'POST', token: tokenOf(token), body: JSON.stringify({ title: input.title, message: input.message, message_type: input.messageType }) }); }
export async function deleteSmsTemplate(token: string | null, id: number): Promise<void> { await apiRequest(`/api/sms/templates/${id}`, { method: 'DELETE', token: tokenOf(token) }); }
export async function addSmsOptOut(token: string | null, phone: string, reason: string): Promise<void> { await apiRequest('/api/sms/opt-outs', { method: 'POST', token: tokenOf(token), body: JSON.stringify({ phone, reason }) }); }
export async function removeSmsOptOut(token: string | null, id: number): Promise<void> { await apiRequest(`/api/sms/opt-outs/${id}`, { method: 'DELETE', token: tokenOf(token) }); }
export async function cancelSmsCampaign(token: string | null, id: number): Promise<void> { await apiRequest(`/api/sms/campaigns/${id}/cancel`, { method: 'POST', token: tokenOf(token) }); }
