import type { SmsCampaign, SmsOptOut, SmsSender, SmsSettings, SmsTemplate } from './types';
const EMPTY: SmsSettings = { configured: false, aligoUserId: '', apiKeyMasked: null, defaultSender: '', adDisplayName: '', moduleEnabled: true, realSendEnabled: false, providerMode: 'mock', providerIsMock: true, providerMisconfigured: false, aligoTestMode: false, outboundServerIpHint: '', aligoApiSettingsUrl: 'https://smartsms.aligo.in/admin/api/spec.html' };
export function normalizeSmsSettings(value: unknown): SmsSettings { if (!value || typeof value !== 'object') return EMPTY; const row = value as Record<string, unknown>; return { ...EMPTY, configured: Boolean(row.configured), aligoUserId: String(row.aligoUserId ?? ''), apiKeyMasked: row.apiKeyMasked == null ? null : String(row.apiKeyMasked), defaultSender: String(row.defaultSender ?? ''), adDisplayName: String(row.adDisplayName ?? ''), moduleEnabled: row.moduleEnabled !== false, realSendEnabled: Boolean(row.realSendEnabled), providerMode: String(row.providerMode ?? 'mock'), providerIsMock: Boolean(row.providerIsMock), providerMisconfigured: Boolean(row.providerMisconfigured), aligoTestMode: Boolean(row.aligoTestMode), outboundServerIpHint: String(row.outboundServerIpHint ?? ''), aligoApiSettingsUrl: String(row.aligoApiSettingsUrl ?? EMPTY.aligoApiSettingsUrl) }; }
export function normalizeSmsSender(value: unknown): SmsSender | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; const id = Number(row.id); if (!Number.isFinite(id)) return null; return { id, senderNumber: String(row.senderNumber ?? row.sender_number ?? ''), label: String(row.label ?? ''), status: String(row.status ?? ''), isDefault: Boolean(row.isDefault ?? row.is_default) }; }
export function normalizeSmsTemplate(value: unknown): SmsTemplate | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; const id = Number(row.id); if (!Number.isFinite(id)) return null; return { id, title: String(row.title ?? ''), message: String(row.message ?? ''), messageType: row.messageType === 'ad' || row.message_type === 'ad' ? 'ad' : 'info' }; }
export function normalizeSmsOptOut(value: unknown): SmsOptOut | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; const id = Number(row.id); if (!Number.isFinite(id)) return null; return { id, phoneMasked: String(row.phoneMasked ?? row.phone_masked ?? ''), reason: row.reason == null ? null : String(row.reason) }; }
export function normalizeSmsCampaign(value: unknown): SmsCampaign | null { if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; const id = Number(row.id); if (!Number.isFinite(id)) return null; return { id, title: String(row.title ?? ''), message: String(row.message ?? ''), messageType: row.messageType === 'ad' || row.message_type === 'ad' ? 'ad' : 'info', senderNumber: String(row.senderNumber ?? row.sender_number ?? ''), targetCount: Number(row.targetCount ?? row.target_count) || 0, successCount: Number(row.successCount ?? row.success_count) || 0, failCount: Number(row.failCount ?? row.fail_count) || 0, skippedCount: Number(row.skippedCount ?? row.skipped_count) || 0, status: String(row.status ?? ''), scheduledAt: row.scheduledAt == null && row.scheduled_at == null ? null : String(row.scheduledAt ?? row.scheduled_at), sentAt: row.sentAt == null && row.sent_at == null ? null : String(row.sentAt ?? row.sent_at), createdAt: String(row.createdAt ?? row.created_at ?? '') }; }
export function estimateSmsBytes(text: string): number { return [...text].reduce((sum, char) => sum + (char.charCodeAt(0) <= 0x7f ? 1 : 2), 0); }
export function detectSmsType(text: string): 'SMS' | 'LMS' { return estimateSmsBytes(text) <= 90 ? 'SMS' : 'LMS'; }
