import { ApiError, apiRequest, resolveApiUrl } from '../../api/client';
import type { CustomerNewsItem, LinkedCustomer, LocalAttachment, NewsAttachment, NewsComment } from './types';
function auth(token: string | null): string { if (!token?.trim()) throw new ApiError('로그인이 필요합니다.', 401); return token.trim(); }
export async function listCustomerNews(token: string | null, scope: 'all' | 'personal', customerId?: number | null) { const q = new URLSearchParams({ scope }); if (customerId) q.set('targetCustomerId', String(customerId)); return apiRequest<CustomerNewsItem[]>(`/api/agent/customer-news?${q}`, { token: auth(token) }); }
export async function listLinkedCustomers(token: string | null) { return apiRequest<LinkedCustomer[]>('/api/agent/customer-app-linked-customers', { token: auth(token) }); }
export async function createCustomerNews(token: string | null, payload: { title: string; content: string; scope: 'all' | 'personal'; targetCustomerId?: number | null; sendPush: boolean; isPinned?: boolean; attachments?: Omit<NewsAttachment, 'id'>[] }) { return apiRequest<{ id: string }>('/api/agent/customer-news', { method: 'POST', token: auth(token), body: JSON.stringify(payload) }); }
export async function updateCustomerNews(token: string | null, id: string, payload: { title: string; content: string; sendPush?: boolean; attachments?: Omit<NewsAttachment, 'id'>[] }) { return apiRequest<{ id: string }>(`/api/agent/customer-news/${encodeURIComponent(id)}`, { method: 'PATCH', token: auth(token), body: JSON.stringify(payload) }); }
export async function deleteCustomerNews(token: string | null, item: CustomerNewsItem) { const q = item.targetCustomerId ? `?targetCustomerId=${item.targetCustomerId}` : ''; await apiRequest(`/api/agent/customer-news/${encodeURIComponent(item.id)}${q}`, { method: 'DELETE', token: auth(token) }); }
export async function listNewsComments(token: string | null, id: string) { return apiRequest<NewsComment[]>(`/api/agent/customer-news/${encodeURIComponent(id)}/comments`, { token: auth(token) }); }
export async function createNewsComment(token: string | null, id: string, content: string) { return apiRequest<NewsComment>(`/api/agent/customer-news/${encodeURIComponent(id)}/comments`, { method: 'POST', token: auth(token), body: JSON.stringify({ content: content.trim() }) }); }
export async function uploadNewsAttachment(token: string | null, asset: LocalAttachment, customerId: number | null): Promise<Omit<NewsAttachment, 'id'>> { const bearer = auth(token); const blob = await fetch(asset.uri).then((response) => response.blob()); const contentType = asset.mimeType || blob.type || 'application/octet-stream'; const presign = await apiRequest<{ uploadUrl: string; objectKey: string; fileUrl: string; putHeaders?: Record<string, string>; kind: 'image' | 'file' }>('/api/agent/customer-news/attachments/presign', { method: 'POST', token: bearer, body: JSON.stringify({ fileName: asset.name, contentType, sizeBytes: asset.size ?? blob.size, customerId }) }); let putOk = false; try { const put = await fetch(presign.uploadUrl, { method: 'PUT', headers: { 'Content-Type': contentType, ...(presign.putHeaders ?? {}) }, body: blob }); putOk = put.ok; } catch { putOk = false; } if (!putOk) { const q = new URLSearchParams({ objectKey: presign.objectKey, contentType, fileSize: String(asset.size ?? blob.size) }); const proxy = await fetch(resolveApiUrl(`/api/agent/customer-news/attachments/upload-proxy?${q}`), { method: 'PUT', headers: { 'Content-Type': contentType, Authorization: `Bearer ${bearer}`, 'X-File-Size': String(asset.size ?? blob.size) }, body: blob }); if (!proxy.ok) throw new ApiError('첨부파일 업로드에 실패했습니다.', proxy.status); } return { kind: presign.kind || asset.kind, url: presign.fileUrl, objectKey: presign.objectKey, fileName: asset.name, mimeType: contentType, size: asset.size ?? blob.size, sortOrder: 0 }; }
