import { ApiError, apiRequest } from '../../api/client';
import type { BillingConfig, BillingCycle, CheckoutQuote, CheckoutSummary, ManageSummary, Subscription } from './types';
function auth(token: string | null): string { if (!token?.trim()) throw new ApiError('로그인이 필요합니다.', 401); return token.trim(); }
export async function getCheckoutSummary(token: string | null) { return apiRequest<CheckoutSummary>('/api/billing/checkout/summary', { token: auth(token) }); }
export async function getQuote(token: string | null, planCode: string, billingCycle: BillingCycle, promotionCode?: string | null) { return apiRequest<{ ok: boolean; quote: CheckoutQuote }>('/api/billing/checkout/quote', { method: 'POST', token: auth(token), body: JSON.stringify({ planCode, billingCycle, promotionCode }) }); }
export async function applyPromotion(token: string | null, code: string, planCode: string, billingCycle: BillingCycle) { return apiRequest<{ ok: boolean; status?: string; subscriptionStatus?: string; message?: string }>('/api/billing/checkout/apply-promotion', { method: 'POST', token: auth(token), body: JSON.stringify({ code, planCode, billingCycle }) }); }
export async function requestPayment(token: string | null, planCode: string, billingCycle: BillingCycle, promotionCode?: string | null) { return apiRequest<{ ok: boolean; status?: string; subscriptionStatus?: string; needsBillingAuth?: boolean; checkoutConfig?: BillingConfig }>('/api/billing/payments/request', { method: 'POST', token: auth(token), body: JSON.stringify({ planCode, billingCycle, promotionCode: promotionCode || undefined, registerOnly: false }) }); }
export async function confirmBillingAuth(token: string | null, authKey: string, customerKey: string) { return apiRequest<{ ok: boolean; hasBillingKey: boolean }>('/api/billing/payment-methods/auth-confirm', { method: 'POST', token: auth(token), body: JSON.stringify({ authKey, customerKey }) }); }
export async function getManageSummary(token: string | null) { return apiRequest<ManageSummary>('/api/billing/manage/summary', { token: auth(token) }); }
export async function changeCycle(token: string | null, billingCycle: BillingCycle) { return apiRequest<{ subscription?: Subscription }>('/api/billing/subscription/billing-cycle', { method: 'PATCH', token: auth(token), body: JSON.stringify({ billingCycle }) }); }
export async function cancelSubscription(token: string | null) { return apiRequest<{ subscription?: Subscription }>('/api/billing/subscription/cancel', { method: 'POST', token: auth(token), body: JSON.stringify({}) }); }
export async function resumeSubscription(token: string | null) { return apiRequest<{ subscription?: Subscription }>('/api/billing/subscription/resume', { method: 'POST', token: auth(token), body: JSON.stringify({}) }); }
