import { useEffect, useMemo, useState } from 'react';
import { Modal, RefreshControl, ScrollView, StyleSheet, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '../../auth/AuthProvider';
import { AppHeader } from '../../components/AppHeader';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { ErrorState } from '../../components/ErrorState';
import { AppText, Badge, Button, Card, Inline, Screen, Stack, TextField, useAppTheme, type AppTheme } from '../../design-system';
import { deleteMyFeatureRequest, listMyFeatureRequestComments, listMyFeatureRequests, submitFeatureRequest } from './featureRequestApi';
import { featureRequestCommentAuthor, featureRequestStatusLabel, formatFeatureRequestDate } from './featureRequestModel';
import type { FeatureRequest } from './types';
const QUERY_KEY = ['feature-requests', 'my'] as const;
export function FeatureRequestsScreen() {
  const { token } = useAuth(); const queryClient = useQueryClient(); const theme = useAppTheme(); const styles = useMemo(() => createStyles(theme), [theme]);
  const [formOpen, setFormOpen] = useState(false); const [expandedId, setExpandedId] = useState<number | null>(null); const [deleting, setDeleting] = useState<FeatureRequest | null>(null);
  const query = useQuery({ queryKey: QUERY_KEY, queryFn: () => listMyFeatureRequests(token), enabled: Boolean(token) });
  const remove = useMutation({ mutationFn: (id: number) => deleteMyFeatureRequest(token, id), onSuccess: async () => { setDeleting(null); await queryClient.invalidateQueries({ queryKey: QUERY_KEY }); } });
  return <View style={styles.root}><AppHeader title="문의요청" /><Screen padded={false}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={() => void query.refetch()} colors={[theme.colors.primary]} tintColor={theme.colors.primary} />}><Inline justify="space-between"><View style={styles.copy}><AppText variant="heading">추가기능 요청하기</AppText><AppText variant="caption">보낸 요청과 담당자 답변을 확인할 수 있습니다.</AppText></View><Button label="작성하기" size="sm" onPress={() => setFormOpen(true)} /></Inline>{query.isError ? <ErrorState title="요청 목록을 불러오지 못했습니다" message={query.error instanceof Error ? query.error.message : '잠시 후 다시 시도해 주세요.'} onRetry={() => void query.refetch()} /> : null}{!query.isLoading && !query.isError && !query.data?.length ? <Card variant="outlined"><AppText color="textSecondary" align="center">등록된 요청이 없습니다.</AppText></Card> : null}{(query.data ?? []).map((request) => { const expanded = request.id === expandedId; return <Card key={request.id} variant="outlined"><Stack gap="md"><Inline justify="space-between" align="flex-start"><View style={styles.copy}><AppText variant="subheading">{request.title || '(제목 없음)'}</AppText><AppText variant="caption">{formatFeatureRequestDate(request.createdAt)}</AppText></View><Badge label={featureRequestStatusLabel(request.status)} tone={request.status === 'done' ? 'success' : request.status === 'reviewed' ? 'info' : 'warning'} /></Inline><AppText color="textSecondary">{request.content}</AppText><Inline wrap><Button label={expanded ? '답변 접기' : request.commentCount ? `답변 보기 (${request.commentCount})` : '답변 보기'} size="sm" variant="secondary" onPress={() => setExpandedId(expanded ? null : request.id)} /><Button label="삭제" size="sm" variant="danger" onPress={() => setDeleting(request)} /></Inline>{expanded ? <FeatureRequestComments requestId={request.id} /> : null}</Stack></Card>; })}</ScrollView></Screen><FeatureRequestForm open={formOpen} token={token} onClose={() => setFormOpen(false)} /><ConfirmDialog open={Boolean(deleting)} title="요청 삭제" message="이 요청을 삭제하시겠습니까?" confirmLabel="삭제" tone="danger" busy={remove.isPending} onCancel={() => setDeleting(null)} onConfirm={() => { if (deleting) remove.mutate(deleting.id); }} /></View>;
}
function FeatureRequestComments({ requestId }: { requestId: number }) { const theme = useAppTheme(); const styles = useMemo(() => createStyles(theme), [theme]); const { token } = useAuth(); const query = useQuery({ queryKey: ['feature-requests', requestId, 'comments'], queryFn: () => listMyFeatureRequestComments(token, requestId), enabled: Boolean(token) }); return <View style={styles.comments}><AppText variant="label">담당자 답변</AppText>{query.isLoading ? <AppText variant="caption">불러오는 중…</AppText> : query.isError ? <AppText color="danger">{query.error instanceof Error ? query.error.message : '답변을 불러오지 못했습니다.'}</AppText> : !query.data?.length ? <AppText variant="caption">아직 등록된 답변이 없습니다.</AppText> : query.data.map((comment) => <View key={comment.id} style={styles.comment}><AppText variant="caption">{featureRequestCommentAuthor(comment)} · {formatFeatureRequestDate(comment.createdAt)}</AppText><AppText>{comment.content}</AppText></View>)}</View>; }
function FeatureRequestForm({ open, token, onClose }: { open: boolean; token: string | null; onClose: () => void }) { const queryClient = useQueryClient(); const theme = useAppTheme(); const styles = useMemo(() => createStyles(theme), [theme]); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); useEffect(() => { if (open) { setTitle(''); setContent(''); } }, [open]); const mutation = useMutation({ mutationFn: () => submitFeatureRequest(token, { title, content }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: QUERY_KEY }); onClose(); } }); return <Modal visible={open} animationType="slide" onRequestClose={onClose}><View style={styles.modal}><View style={styles.modalHeader}><AppText variant="heading">추가기능 요청 작성</AppText><Button label="닫기" size="sm" variant="ghost" onPress={onClose} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Card variant="outlined"><Stack gap="md"><TextField label="제목" required value={title} onChangeText={setTitle} maxLength={200} /><TextField label="내용" required value={content} onChangeText={setContent} multiline numberOfLines={6} maxLength={8000} />{mutation.error ? <AppText color="danger">{mutation.error instanceof Error ? mutation.error.message : '등록하지 못했습니다.'}</AppText> : null}<Button label="등록" fullWidth loading={mutation.isPending} disabled={!title.trim() || !content.trim()} onPress={() => mutation.mutate()} /></Stack></Card></ScrollView></View></Modal>; }
function createStyles(theme: AppTheme) { return StyleSheet.create({ root: { flex: 1 }, content: { padding: theme.spacing.lg, paddingBottom: theme.spacing.xl, gap: theme.spacing.md }, copy: { flex: 1, gap: theme.spacing.xs }, comments: { paddingTop: theme.spacing.md, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: theme.colors.border, gap: theme.spacing.sm }, comment: { padding: theme.spacing.md, borderRadius: theme.radius.md, backgroundColor: theme.colors.surfaceSubtle, gap: theme.spacing.xs }, modal: { flex: 1, backgroundColor: theme.colors.background }, modalHeader: { minHeight: 64, paddingHorizontal: theme.spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: theme.colors.border, backgroundColor: theme.colors.surface } }); }
